name: Test
on:
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'Gemfile'
      - 'Rakefile'
      - 'sin_fast_blank.gemspec'
      - '**/*.rb'
  schedule:
    - cron: '0 12 * * 5'
permissions:
  contents: read
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - 'ruby-head'
          - 'jruby-9.3'
          - 'jruby-9.4'
          - 'jruby-head'
          - 'truffleruby-22'
          - 'truffleruby-23'
          - 'truffleruby-24'
          - 'truffleruby-head'
          - 'truffleruby+graalvm-22'
          - 'truffleruby+graalvm-23'
          - 'truffleruby+graalvm-24'
          - 'truffleruby+graalvm-head'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run compile
        run: bundle exec rake compile
      - name: Run tests
        run: bundle exec rake test
  test-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.4'
          - 'jruby-9.4'
          - 'truffleruby-24'
          - 'truffleruby+graalvm-24'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run compile
        run: bundle exec rake compile
      - name: Run tests
        run: bundle exec rake test
  test-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 'mingw'
          - 'mswin'
          - 'ucrt'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run compile
        run: bundle exec rake compile
      - name: Run tests
        run: bundle exec rake test
